### ISSUE TITLE
Prefer setImmediate over process.nextTick

### ISSUE THREAD

**Issue by MattMcFarland** [yoshuawuyts/nanotick#7]
`setImmediate` is newer than `process.nextTick` and will **always** exist when `process.nextTick` does - Both are using node.js - So if you check for `process.nextTick` **first** - `setImmediate` will always be `falsey` if `process.nextTick` is `falsey`.

`setImmediate` is better for queuing callbacks

http://stackoverflow.com/questions/17502948/nexttick-vs-setimmediate-visual-explanation

https://nodejs.org/api/timers.html#timers_setimmediate_callback_args

Most importantly:  **setImmediate** callbacks are fired off the event loop, once per iteration in the order that they were queued.  **nextTick** callbacks, however, are always fired immediately after the current code is done executing and *before* going back to the event loop.

Is this preferred behavior? If so we should either drop setImmediate alltogether (but if we want to use queueing, setImmediate is better)

Specifically, I recommend reverting the changes made to delayed function back to this:

```javascript
var delay = (typeof setImmediate !== 'undefined')
  ? setImmediate : (typeof process !== 'undefined' && process.nextTick)
  ? process.nextTick : setTimeout
```

**Comment by yoshuawuyts** [comment]
The reason why I put `process.nextTick` as the preferred method in Node is because I know it's being used everywhere - over the years I've developed an intuition for how it works.

`setImmediate` on the other hand originates from a spec that appears to have lost traction; it doesn't seem to be adopted by any newer thing; iirc only IE / Edge has implemented it. From what I remember there can also be things where `fs` events never resolve because the loop never exits causing weird issues. This might not be an issue for run of the mill JS apps, but def becomes a problem for `Electron` apps. It's def still better to use on the browser than `setTimeout 0` tho.

I think it might be a matter of taste, but in this case I think going with the known, intuitive thing might make more sense (at least for me) - does that make sense?

**Comment by yoshuawuyts** [comment]
The "never exits" thing was I believe a recursive `setImmediate` call which causes the `fs` layer of node to never be hit

**Comment by yoshuawuyts** [comment]
Oh lol actually it's the other way around hmmm maybe yeah we should change
it?

**Comment by MattMcFarland** [comment]
@yoshuawuyts: I was looking at this from the context of node.js - not really the browser - so in the context of node.js you will always see process.nextTick before you see setImmediate, and therefore setImmediate will never be used.  Because setImmediate is for queuing, I was hoping that using it could possibly give us room to knock out issue #3 as well

For browser I honestly wasnt aware setImmediate was in use, and figured setTimeout would be used.  

Anyway, I am now more confused :S lol

**Comment by yoshuawuyts** [comment]
I think we're getting the behavior we want now actually - closing (:

**Comment by MattMcFarland** [comment]
Thanks Yosh!  

```javascript
var delay = (typeof window !== 'undefined' && window.document)
  ? (typeof setImmediate !== 'undefined')
    ? setImmediate
    : setTimeout
  : eval('process.nextTick')
```

So does eval being used there prevent process.nextTick from being prepackaged with browserify??? If so that is really neat.

**Comment by yoshuawuyts** [comment]
Yep

**Comment by MattMcFarland** [comment]
Nice!! I didnt know you could do that :D
